"""Stage 3: parametrized edge-case sweep.

Runs bracket_model.build_bracket across a range of values for flange
length, bend radius, sheet thickness, and bend angle -- including
deliberately hostile edge cases -- and reports pass/fail for each. Plate
length/width and hole layout are held at Stage 2's baseline values since
they aren't in scope for this sweep (varying flange length/bend
radius/gauge/angle is what Stage 3 asked for).

This never stops at the first failure: every case runs, every result is
logged. That's the point of the exercise -- find out where the geometry
actually breaks, not paper over it.

Run with:
    /opt/miniconda3/envs/freecad/bin/freecadcmd scripts/test_matrix.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import add_sheetmetal_to_path

add_sheetmetal_to_path()

from bracket_model import build_bracket

# Baseline (Stage 2) values, held fixed except for the parameter(s) each
# case is exercising.
BASE = dict(
    plate_length=100.0,
    plate_width=60.0,
    thickness=2.0,
    flange_length=30.0,
    bend_angle=90.0,
    bend_radius=2.0,
    k_factor=0.38,
    hole_dia=6.0,
    hole_x=30.0,
    hole_y=15.0,
)

CASES = [
    ("baseline", {}),
    ("short_flange (5mm, still > radius+thickness=4mm)", {"flange_length": 5.0}),
    ("very_short_flange (1mm, < radius+thickness=4mm)", {"flange_length": 1.0}),
    ("zero_flange (0mm)", {"flange_length": 0.0}),
    ("negative_flange (-5mm)", {"flange_length": -5.0}),
    ("tight_radius (0.1mm)", {"bend_radius": 0.1}),
    ("near_zero_radius (0.01mm)", {"bend_radius": 0.01}),
    ("zero_radius (0mm)", {"bend_radius": 0.0}),
    ("thin_gauge (0.3mm)", {"thickness": 0.3}),
    ("very_thin_gauge (0.05mm)", {"thickness": 0.05}),
    ("thick_gauge_small_radius (T=8mm, R=2mm -- radius < thickness)", {"thickness": 8.0}),
    ("thick_gauge_proper_radius (T=8mm, R=8mm)", {"thickness": 8.0, "bend_radius": 8.0}),
    ("large_bend_angle (150deg)", {"bend_angle": 150.0}),
    ("small_bend_angle (15deg)", {"bend_angle": 15.0}),
    ("combo_stress (FL=2mm, R=1.8mm, T=2mm -- flange barely clears bend)", {"flange_length": 2.0, "bend_radius": 1.8}),
]


def main():
    results = []
    for name, overrides in CASES:
        params = {**BASE, **overrides}
        result = build_bracket(
            doc_name="MatrixCase",
            export_dir=None,  # sweep is about geometry validity, not file output
            **params,
        )
        results.append((name, params, result))
        status = "PASS" if result["ok"] else "FAIL"
        print(f"[{status}] {name}")
        if result["ok"]:
            m = result["metrics"]
            print(
                f"         flat={m['flat_length']}x{m['flat_width']}mm "
                f"(expected {m['expected_flat_length']}mm, diff {m['flat_length_diff']}mm), "
                f"volume={m['folded_volume']}mm^3"
            )
        else:
            print(f"         ERROR: {result['error']}")

    n_pass = sum(1 for _, _, r in results if r["ok"])
    n_fail = len(results) - n_pass
    print(f"\n{n_pass} passed, {n_fail} failed out of {len(results)} cases")

    write_report(results)


def write_report(results):
    report_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "reports")
    os.makedirs(report_dir, exist_ok=True)
    path = os.path.join(report_dir, "stage3_test_matrix.md")

    lines = [
        "# Stage 3 edge-case test matrix",
        "",
        "Generated by `scripts/test_matrix.py`. Baseline params (Stage 2's",
        "bracket) held fixed except for the field(s) each case overrides.",
        "",
        "| Case | Overrides | Result | Detail |",
        "|---|---|---|---|",
    ]
    for name, params, result in results:
        overrides = {k: v for k, v in params.items() if BASE.get(k) != v}
        overrides_str = ", ".join(f"{k}={v}" for k, v in overrides.items()) or "(none -- baseline)"
        if result["ok"]:
            m = result["metrics"]
            detail = (
                f"flat={m['flat_length']}x{m['flat_width']}mm, "
                f"diff={m['flat_length_diff']}mm, volume={m['folded_volume']}mm^3"
            )
            status = "PASS"
        else:
            detail = result["error"].replace("|", "\\|")
            status = "FAIL"
        lines.append(f"| {name} | {overrides_str} | {status} | {detail} |")

    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nReport written: {path}")


main()
