package com.digitalsolutions.diagnosticlab.domain.model

enum class UserRole {
    PATIENT, PHLEBOTOMIST, LABORATORY, ADMIN
}

enum class Relation {
    MYSELF, SPOUSE, FATHER, MOTHER, SON, DAUGHTER, OTHER
}

enum class BookingStatus {
    PENDING_PAYMENT,
    CONFIRMED,
    PHLEBOTOMIST_ASSIGNED,
    PHLEBOTOMIST_ON_THE_WAY,
    ARRIVED,
    SAMPLE_COLLECTED,
    SAMPLE_IN_TRANSIT,
    RECEIVED_AT_LAB,
    PROCESSING,
    REPORT_READY,
    REPORT_DELIVERED,
    CANCELLED_BY_PATIENT,
    CANCELLED_BY_LAB,
    REJECTED_RECOLLECTION_NEEDED
}

enum class AssignmentStatus {
    UNASSIGNED, ASSIGNED, ACCEPTED, REJECTED, ON_THE_WAY, ARRIVED, SAMPLE_COLLECTED, COMPLETED, CANCELLED
}

enum class PaymentMethod { ONLINE, CASH }

enum class PaymentStatus { PENDING, PROCESSING, SUCCESSFUL, FAILED, CASH_SELECTED }

enum class SampleStatus {
    COLLECTED, HANDED_OVER, IN_TRANSIT, RECEIVED_AT_LAB, ACCEPTED, REJECTED, PROCESSING, COMPLETED
}

enum class SampleRejectionReason {
    INSUFFICIENT_SAMPLE, INCORRECT_SAMPLE, DAMAGED_SAMPLE, LABEL_MISMATCH, OTHER
}

enum class ReportStatus { PENDING, READY, VERIFIED, DELIVERED }

enum class ComplaintCategory {
    BOOKING_ISSUE, PAYMENT_ISSUE, COLLECTION_DELAY, REPORT_DELAY, STAFF_BEHAVIOUR, APP_ISSUE, OTHER
}

enum class ComplaintStatus { OPEN, ASSIGNED, IN_PROGRESS, RESOLVED, CLOSED }

enum class NotificationType {
    BOOKING_CONFIRMED, PAYMENT_CONFIRMED, PHLEBOTOMIST_ASSIGNED, PHLEBOTOMIST_ACCEPTED,
    PHLEBOTOMIST_ON_THE_WAY, PHLEBOTOMIST_ARRIVED, SAMPLE_COLLECTED, SAMPLE_RECEIVED_AT_LAB,
    SAMPLE_PROCESSING, REPORT_READY, REPORT_DELIVERED, COMPLAINT_UPDATE, GENERAL
}

enum class AppLanguage(val tag: String) {
    ENGLISH("en"), TAMIL("ta")
}
